CREATE TABLE IF NOT EXISTS `roles` (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`slug` VARCHAR(100) NOT NULL,
	`module` VARCHAR(100) NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`created_by` INTEGER NOT NULL DEFAULT 0,
	`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`updated_by` INTEGER NOT NULL DEFAULT 0,
	`deleted_at` TIMESTAMP NULL,
	`deleted_by` INTEGER NULL
);
